# Generated by Django 5.1.7 on 2025-03-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_rename_weight_weightrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightrecord',
            old_name='value',
            new_name='weight',
        ),
    ]
